### ISSUE TITLE
deprecated packages and what happens ? 

### ISSUE THREAD

**Issue by lshep** [seandavi/BiocPkgTools#8]
https://support.bioconductor.org/p/101831/

**Comment by seandavi** [comment]
The deprecation process is relatively new, so we haven't talked about it much. I'd vote for maintaining landing pages for deprecated packages, to be honest. The content of the landing page could simply say that the package is no longer supported, but things like github URLs, author names, descriptions, etc., are potentially all still valid. The landing page could resolve to /archive/ instead of /release/ or /devel/, but whatever you all think makes sense. A DOI is to a stable resource, so we should keep that.

**Comment by lshep** [comment]
I think this might be okay to close -  as mentioned in the support issue -  if a package is removed it gets added to the removed package page -  if a package isn't found in the release or devel of Bioconductor the short url redirects to this page that has a link to the last stable version - but wasn't sure if there was more to what we were thinking with this?

**Comment by seandavi** [comment]
Makes sense.
